apiVersion: kubedb.com/v1alpha1
kind: MySQL
metadata:
  name: mydb
spec:
  version: "5.7.25"
  topology:
    mode: GroupReplication
    group:
      name: "ab002fc3-c412-4d18-b1d4-66c1fbfbbc9b"
      baseServerID: 100
  storageType: "Durable"
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
  backupSchedule:
    cronExpression: "@every 3m"
    local:
        mountPath: /repo
        hostPath:
          path: /backup
          type: DirectoryOrCreate
