apiVersion: "cloudowski.com/v1"
kind: ShoppingList
metadata:
  name: zakupy-2
spec:
  store: ropuszka
  #  priority: quality
  list:
      - name: mleko
        count: 1
      - name: naleśniki
        count: 4
