apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: gitea
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: gitea-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: gitea-{{ .Release.Name }}
    spec:
      containers:
      - name: gitea
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 3000
          name: web
        - containerPort: 22
          name: ssh

        env:
        - name: USER_UID
          value: "1000"
        - name: USER_GID
          value: "1000"

        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 3
        
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-config

