apiVersion: v1
kind: Service
metadata:
  labels:
    app: fussy
  name: fussy
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32222
  selector:
    app: fussy
